services:
  sovia:
    image: sovia
    container_name: sovia
    restart: always
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    network_mode: host
    volumes:
      - db:/data
volumes:
  db:
